"""add bias to _j

Revision ID: 10009e1dc6e8
Revises: a8a3edb95e32
Create Date: 2020-10-08 09:56:31.974199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10009e1dc6e8'
down_revision = 'a8a3edb95e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_aggregations_j', sa.Column('bias_value', sa.Integer(), nullable=True))
    op.add_column('metric_properties_j', sa.Column('bias_property', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric_properties_j', 'bias_property')
    op.drop_column('metric_aggregations_j', 'bias_value')
    # ### end Alembic commands ###
