"""metrics

Revision ID: 1742b18349a4
Revises: 
Create Date: 2020-10-03 12:47:07.873475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1742b18349a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('population_id', mysql.TINYINT(), nullable=False),
    sa.Column('properties_id', sa.Integer(), nullable=False),
    sa.Column('aggregations_id', sa.Integer(), nullable=False),
    sa.Column('bias_value', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fill_id', 'population_id', 'properties_id', 'aggregations_id'),
    mysql_partition_by='KEY(fill_id)'
    )
    op.create_table('metric_coverage',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('properties_id', sa.Integer(), nullable=False),
    sa.Column('total_with_properties', sa.Integer(), nullable=True),
    sa.Column('total_sitelinks_with_properties', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('fill_id', 'properties_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric_coverage')
    op.drop_table('metric')
    # ### end Alembic commands ###
