"""indexing on label

Revision ID: 8be215fc84b3
Revises: 82d89f52797f
Create Date: 2020-11-11 10:22:27.858929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be215fc84b3'
down_revision = '82d89f52797f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_label_lang'), 'label', ['lang'], unique=False)
    op.create_index(op.f('ix_label_qid'), 'label', ['qid'], unique=False)
    op.create_index(op.f('ix_label_misc_lang'), 'label_misc', ['lang'], unique=False)
    op.create_index(op.f('ix_label_misc_src'), 'label_misc', ['src'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_label_misc_src'), table_name='label_misc')
    op.drop_index(op.f('ix_label_misc_lang'), table_name='label_misc')
    op.drop_index(op.f('ix_label_qid'), table_name='label')
    op.drop_index(op.f('ix_label_lang'), table_name='label')
    # ### end Alembic commands ###
