"""human_id is foreign

Revision ID: a6e770c96950
Revises: c63ddfe9d42d
Create Date: 2020-09-30 15:16:49.182608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e770c96950'
down_revision = 'c63ddfe9d42d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('hs_fk', 'human_sitelink', 'human', ['human_id'], ['qid'])
    op.create_foreign_key('hp_fk', 'human_property', 'human', ['human_id'], ['qid'])
    op.create_foreign_key('ho_fk', 'human_country', 'human', ['human_id'], ['qid'])
    op.create_foreign_key('hc_fk', 'human_occupation', 'human', ['human_id'], ['qid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hs_fk', 'human_sitelink', type_='foreignkey')
    op.drop_constraint('hp_fk', 'human_property', type_='foreignkey')
    op.drop_constraint('ho_fk', 'human_occupation', type_='foreignkey')
    op.drop_constraint('hc_fk', 'human_country', type_='foreignkey')
    # ### end Alembic commands ###
