"""humans

Revision ID: a8a3edb95e32
Revises: 1742b18349a4
Create Date: 2020-10-03 14:23:49.185240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8a3edb95e32'
down_revision = '1742b18349a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_country',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('fill_id', 'human_id', 'country')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('type', mysql.TINYTEXT(), nullable=True),
    sa.Column('label', mysql.TINYTEXT(), nullable=True),
    sa.Column('url', mysql.TINYTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_code'), 'project', ['code'], unique=True)
    op.create_table('human',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('qid', sa.Integer(), nullable=False),
    sa.Column('year_of_birth', sa.SMALLINT(), nullable=True),
    sa.Column('year_of_death', sa.SMALLINT(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('sitelink_count', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('fill_id', 'qid')
    )
    op.create_table('human_occupation',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('fill_id', 'human_id', 'occupation')
    )
    op.create_table('human_property',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('property_p', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('fill_id', 'human_id', 'property_p')
    )
    op.create_table('human_sitelink',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('sitelink', mysql.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('fill_id', 'human_id', 'sitelink')
    )
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fill_id', sa.Integer(), nullable=True),
    sa.Column('qid', sa.Integer(), nullable=True),
    sa.Column('lang', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('label', mysql.VARCHAR(length=512), nullable=True),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occupation_parent',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.Integer(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('fill_id', 'occupation', 'parent')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('occupation_parent')
    op.drop_table('label')
    op.drop_table('human_sitelink')
    op.drop_table('human_property')
    op.drop_table('human_occupation')
    op.drop_table('human')
    op.drop_index(op.f('ix_project_code'), table_name='project')
    op.drop_table('project')
    op.drop_table('human_country')
    # ### end Alembic commands ###
