"""create metrics, humans, from scratch, labels with property

Revision ID: c57dc35547ba
Revises: 
Create Date: 2020-10-09 13:49:44.752317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c57dc35547ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', mysql.TINYINT(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fill_date'), 'fill', ['date'], unique=False)
    op.create_table('human_country',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('fill_id', 'human_id', 'country')
    )
    op.create_table('metric',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('population_id', mysql.TINYINT(), nullable=False),
    sa.Column('properties_id', sa.Integer(), nullable=False),
    sa.Column('aggregations_id', sa.Integer(), nullable=False),
    sa.Column('bias_value', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fill_id', 'population_id', 'properties_id', 'aggregations_id'),
    mysql_partition_by='KEY(fill_id)'
    )
    op.create_table('metric_aggregations_j',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bias_value', sa.Integer(), nullable=True),
    sa.Column('aggregations', sa.JSON(), nullable=True),
    sa.Column('aggregations_len', mysql.TINYINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_aggregations_n',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('aggregation_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'property', 'value', 'aggregation_order')
    )
    op.create_table('metric_properties_j',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bias_property', sa.Integer(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('properties_len', mysql.TINYINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_properties_n',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property', sa.Integer(), nullable=False),
    sa.Column('property_order', mysql.TINYINT(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'property', 'property_order')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('type', mysql.TINYTEXT(), nullable=True),
    sa.Column('label', mysql.TINYTEXT(), nullable=True),
    sa.Column('url', mysql.TINYTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_code'), 'project', ['code'], unique=True)
    op.create_table('human',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('qid', sa.Integer(), nullable=False),
    sa.Column('year_of_birth', sa.SMALLINT(), nullable=True),
    sa.Column('year_of_death', sa.SMALLINT(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('sitelink_count', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('fill_id', 'qid')
    )
    op.create_table('human_occupation',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('fill_id', 'human_id', 'occupation')
    )
    op.create_table('human_property',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('property_p', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('fill_id', 'human_id', 'property_p')
    )
    op.create_table('human_sitelink',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('sitelink', mysql.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('fill_id', 'human_id', 'sitelink')
    )
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fill_id', sa.Integer(), nullable=True),
    sa.Column('qid', sa.Integer(), nullable=True),
    sa.Column('lang', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('label', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('property', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_property'), 'label', ['property'], unique=False)
    op.create_table('metric_coverage',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('properties_id', sa.Integer(), nullable=False),
    sa.Column('total_with_properties', sa.Integer(), nullable=True),
    sa.Column('total_sitelinks_with_properties', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('fill_id', 'properties_id')
    )
    op.create_table('occupation_parent',
    sa.Column('fill_id', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.Integer(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('fill_id', 'occupation', 'parent')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('occupation_parent')
    op.drop_table('metric_coverage')
    op.drop_index(op.f('ix_label_property'), table_name='label')
    op.drop_table('label')
    op.drop_table('human_sitelink')
    op.drop_table('human_property')
    op.drop_table('human_occupation')
    op.drop_table('human')
    op.drop_index(op.f('ix_project_code'), table_name='project')
    op.drop_table('project')
    op.drop_table('metric_properties_n')
    op.drop_table('metric_properties_j')
    op.drop_table('metric_aggregations_n')
    op.drop_table('metric_aggregations_j')
    op.drop_table('metric')
    op.drop_table('human_country')
    op.drop_index(op.f('ix_fill_date'), table_name='fill')
    op.drop_table('fill')
    # ### end Alembic commands ###
