"""add sitelink_count to human

Revision ID: c63ddfe9d42d
Revises: fcde655d33a7
Create Date: 2020-09-30 09:00:32.011147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63ddfe9d42d'
down_revision = 'fcde655d33a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human', sa.Column('sitelink_count', sa.SMALLINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('human', 'sitelink_count')
    # ### end Alembic commands ###
