"""human raw tables

Revision ID: fcde655d33a7
Revises: c39522941731
Create Date: 2020-09-29 13:59:25.100908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcde655d33a7'
down_revision = 'c39522941731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fill_id', sa.Integer(), nullable=True),
    sa.Column('qid', sa.Integer(), nullable=True),
    sa.Column('year_of_birth', sa.SMALLINT(), nullable=True),
    sa.Column('year_of_death', sa.SMALLINT(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_fill_id'), 'human', ['fill_id'], unique=False)
    op.create_index(op.f('ix_human_qid'), 'human', ['qid'], unique=False)
    op.create_table('human_country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fill_id', sa.Integer(), nullable=True),
    sa.Column('human_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_country_fill_id'), 'human_country', ['fill_id'], unique=False)
    op.create_table('human_occupation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fill_id', sa.Integer(), nullable=True),
    sa.Column('human_id', sa.Integer(), nullable=True),
    sa.Column('occupation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_occupation_fill_id'), 'human_occupation', ['fill_id'], unique=False)
    op.create_table('human_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fill_id', sa.Integer(), nullable=True),
    sa.Column('human_id', sa.Integer(), nullable=True),
    sa.Column('property_p', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_property_fill_id'), 'human_property', ['fill_id'], unique=False)
    op.create_table('human_sitelink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fill_id', sa.Integer(), nullable=True),
    sa.Column('human_id', sa.Integer(), nullable=True),
    sa.Column('sitelink', mysql.TINYTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_sitelink_fill_id'), 'human_sitelink', ['fill_id'], unique=False)
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fill_id', sa.Integer(), nullable=True),
    sa.Column('qid', sa.Integer(), nullable=True),
    sa.Column('lang', mysql.TINYTEXT(), nullable=True),
    sa.Column('label', mysql.MEDIUMTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_fill_id'), 'label', ['fill_id'], unique=False)
    op.create_index(op.f('ix_label_qid'), 'label', ['qid'], unique=False)
    op.create_table('occupation_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fill_id', sa.Integer(), nullable=True),
    sa.Column('occupation', sa.Integer(), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fill_id'], ['fill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupation_parent_fill_id'), 'occupation_parent', ['fill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('occupation_parent')
    op.drop_table('label')
    op.drop_table('human_sitelink')
    op.drop_table('human_property')
    op.drop_table('human_occupation')
    op.drop_table('human_country')
    op.drop_table('human')
    # op.drop_index(op.f('ix_occupation_parent_fill_id'), table_name='occupation_parent')
    # op.drop_index(op.f('ix_label_qid'), table_name='label')
    # op.drop_index(op.f('ix_label_fill_id'), table_name='label')
    # op.drop_index(op.f('ix_human_sitelink_fill_id'), table_name='human_sitelink')
    # op.drop_index(op.f('ix_human_property_fill_id'), table_name='human_property')
    # op.drop_index(op.f('ix_human_occupation_fill_id'), table_name='human_occupation')
    # op.drop_index(op.f('ix_human_country_fill_id'), table_name='human_country')
    # op.drop_index(op.f('ix_human_qid'), table_name='human')
    # op.drop_index(op.f('ix_human_fill_id'), table_name='human')
    # ### end Alembic commands ###
